#!/bin/bash
echo "{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{"
rm -rf __repo_1__

# commit and push
git add *
git commit -m "_publish: update at `date`"
git push origin master

echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

# change url and push to another repository
mkdir __repo_1__
hugo -b "https://etfire.gitee.io/home/" -d "__repo_1__"
cd __repo_1__
git init
git remote add origin https://gitee.com/etfire/home.git
git add *
git commit -m "_publish: update at `date`"
git push origin master --force

echo "}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}"

echo "open gitee refresh page"
python -mwebbrowser https://gitee.com/etfire/home/pages
